Failure # 1 (occurred at 2024-08-09_15-01-14)
[36mray::PPO.train()[39m (pid=32871, ip=127.0.0.1, actor_id=f528b66ddd184ae7d925ad9801000000, repr=PPO)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 328, in train
    result = self.step()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 873, in step
    train_results, train_iter_ctx = self._run_one_training_iteration()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 3154, in _run_one_training_iteration
    results = self.training_step()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 428, in training_step
    return self._training_step_old_and_hybrid_api_stacks()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 562, in _training_step_old_and_hybrid_api_stacks
    train_batch = synchronous_parallel_sample(
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 97, in synchronous_parallel_sample
    sampled_data = worker_set.foreach_worker(
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/env/env_runner_group.py", line 849, in foreach_worker
    _handle_remote_call_result_errors(
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/env/env_runner_group.py", line 1184, in _handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(ValueError): [36mray::RolloutWorker.apply()[39m (pid=32900, ip=127.0.0.1, actor_id=3d623c781a4ba8b03010ff3101000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x15f803bb0>)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 192, in apply
    raise e
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 181, in apply
    return func(self, *args, **kwargs)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 99, in <lambda>
    (lambda w: w.sample())
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 685, in sample
    batches = [self.input_reader.next()]
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 91, in next
    batches = [self.get_data()]
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 273, in get_data
    item = next(self._env_runner)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 348, in run
    outputs = self.step()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 367, in step
    ) = self._base_env.poll()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env.py", line 634, in poll
    ) = env_state.poll()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env.py", line 837, in poll
    self.reset()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env.py", line 921, in reset
    raise e
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env.py", line 915, in reset
    obs_and_infos = self.env.reset(seed=seed, options=options)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/env/wrappers/pettingzoo_env.py", line 214, in reset
    obs, info = self.par_env.reset(seed=seed, options=options)
ValueError: too many values to unpack (expected 2)
