Failure # 1 (occurred at 2024-05-17_10-46-49)
[36mray::PPO.train()[39m (pid=21346, ip=127.0.0.1, actor_id=25a817e6f07897e8e547edd801000000, repr=PPO)
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/tune/trainable/trainable.py", line 339, in train
    result = self.step()
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/algorithms/algorithm.py", line 852, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/algorithms/algorithm.py", line 3042, in _run_one_training_iteration
    results = self.training_step()
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 407, in training_step
    train_batch = synchronous_parallel_sample(
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/execution/rollout_ops.py", line 83, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/worker_set.py", line 705, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/worker_set.py", line 78, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(TypeError): [36mray::RolloutWorker.apply()[39m (pid=21440, ip=127.0.0.1, actor_id=f54df0667caac6812eadf3fb01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x347bde400>)
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/utils/actor_manager.py", line 189, in apply
    raise e
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/utils/actor_manager.py", line 178, in apply
    return func(self, *args, **kwargs)
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/execution/rollout_ops.py", line 84, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/rollout_worker.py", line 694, in sample
    batches = [self.input_reader.next()]
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/sampler.py", line 91, in next
    batches = [self.get_data()]
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/sampler.py", line 276, in get_data
    item = next(self._env_runner)
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 344, in run
    outputs = self.step()
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 370, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 536, in _process_observations
    policy_id: PolicyID = episode.policy_for(agent_id)
  File "/Users/joykhera/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/episode_v2.py", line 120, in policy_for
    policy_id = self._agent_to_policy[agent_id] = self.policy_mapping_fn(
TypeError: <lambda>() takes 1 positional argument but 2 were given
