Failure # 1 (occurred at 2024-08-08_13-31-45)
[36mray::PPO.train()[39m (pid=20437, ip=127.0.0.1, actor_id=4bf265bac992d7f462ee1cab01000000, repr=PPO)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 328, in train
    result = self.step()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 873, in step
    train_results, train_iter_ctx = self._run_one_training_iteration()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 3154, in _run_one_training_iteration
    results = self.training_step()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 428, in training_step
    return self._training_step_old_and_hybrid_api_stacks()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 562, in _training_step_old_and_hybrid_api_stacks
    train_batch = synchronous_parallel_sample(
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 97, in synchronous_parallel_sample
    sampled_data = worker_set.foreach_worker(
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/env/env_runner_group.py", line 849, in foreach_worker
    _handle_remote_call_result_errors(
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/env/env_runner_group.py", line 1184, in _handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(TypeError): [36mray::RolloutWorker.apply()[39m (pid=20496, ip=127.0.0.1, actor_id=a1ea76f9b464760344962deb01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x145c04a90>)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 192, in apply
    raise e
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 181, in apply
    return func(self, *args, **kwargs)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 99, in <lambda>
    (lambda w: w.sample())
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 685, in sample
    batches = [self.input_reader.next()]
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 91, in next
    batches = [self.get_data()]
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 273, in get_data
    item = next(self._env_runner)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 348, in run
    outputs = self.step()
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 374, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 540, in _process_observations
    policy_id: PolicyID = episode.policy_for(agent_id)
  File "/Users/joykhera/Library/Caches/pypoetry/virtualenvs/evolution-E7IEFu2R-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/episode_v2.py", line 119, in policy_for
    policy_id = self._agent_to_policy[agent_id] = self.policy_mapping_fn(
TypeError: get_policy_mapping_fn() got an unexpected keyword argument 'worker'
